---
driver:
  name: vagrant
  provider: virtualbox
  linked_clone: true

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 12.20.3

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: server
    driver:
      vm_hostname: server.rancher.local
      network:
      - ["private_network", {ip: "192.168.33.33"}]
      - ["forwarded_port", {guest: 8080, host: 8080}]
    run_list:
      - recipe[cb_rancherhost::server]
    verifier:
      inspec_tests:
        - test/smoke/server
    attributes:

  - name: agent
    driver:
      vm_hostname: agent.rancher.local
      network:
      - ["private_network", {ip: "192.168.33.44"}]
    run_list:
      - recipe[cb_rancherhost::agent]
    verifier:
      inspec_tests:
        - test/smoke/agent
    attributes:
      rancher:
        server:
          host: 192.168.33.33
